#!/bin/bash

echo "########################################################"
echo "Trying to generate client release from build folder..."
echo "########################################################"
echo "create dist folder..."
mkdir -p dist/core/client
mkdir -p dist/core/common
mkdir -p dist/core/external/simple-serial-port-1.03/lib
echo "copy library..."
cp build/libsm-client.a dist/
echo "copy headers..."
cp -r core/client/inc dist/core/client
cp -r core/common dist/core
cp -r core/external/simple-serial-port-1.03/lib/inc dist/core/external/simple-serial-port-1.03/lib
echo "Done!"
echo "########################################################"

